
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
{	
  //揉捏在最低点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
//揉捏在最高点电机正转，速度改变
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //20
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  //30
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //40
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
   //揉捏在随机位置电机正转，速度1-2-3改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
 //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
 
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  //60
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //70
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,25,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  //80
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //90
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},



{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
   //100
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
   //110
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
//揉捏在最高点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //120
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //130
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  //140
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //160
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},

 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  
//  
//		//揉捶同步到底部（低速）
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		/////////////////////////////////////////////////////////////////////////////
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//1
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//2
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//3
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//4
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//5
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//6
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//7
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//8
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//9
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2},
//		//10
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		//11
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		//12
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		//13
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		//14
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//
//
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},	
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},							
//                //modify 20130709
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,100,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//                
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1},
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//                
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		////////////////////////////////////////////////////////////////////////////
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},	
//		//肩部捶打
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,7,3,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,6,4,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,5,5,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,1,4,SPEED_4},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,8,2,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MAX,0,KNOCK_RUN_STOP,9,1,SPEED_3},
//		//Neck Knead
//		////
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,5,KNEAD_RUN_STOP_AT_MAX,2,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4},
//
//                
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//捶击定位（窄中宽）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//捶击定位（窄中宽）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MED,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_RUN_STOP_AT_MAX,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		//揉捏
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+15,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		//向上行走15，捶击定位（窄）80
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+45,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		//向上行走15，捶击定位（窄）
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},	
//		//向下揉捏到底
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_4},
//		//定点轻敲5次
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲到顶部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//定点低速揉捏5
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_1},
//		//向下捶击行走到肩部	////
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},
//		//向上捶击行走到顶部	100
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,KNOCK_STOP,20,0,SPEED_1},
//		//向下捶击行走到肩部	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		//定点捶击2秒
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,0,KNEAD_STOP,0,KNOCK_RUN,20,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		//定点揉捏5
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3},
//		//向下捶击行走到底	
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,4,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//向上揉捶行走25/115
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+25,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+50,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		//向下揉捏到底
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_WIDTH,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//变速揉摧同步到底
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		//定点揉捏5
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},
//		//窄指压到顶
//		{BACK_SUB_MODE_PRESS,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_1},
//		
//		//070315测试/133
//		//颈部动作组合
//		
//		/*
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		//低速敲打到底部/141
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_4},		
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_5},	
//                
//                //搓背  
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
////  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_6},
//
//                
//		//腰部变速敲打161
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_5},
//		//行走揉摧同步182
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_6},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_5},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_4},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		{BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_2},
//		//颈部动作组合194
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1},
//		//轻敲到肩部//208
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲到顶部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		//轻敲			////////////////////////////////////
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+60,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PressNeck,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		//轻敲
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_5},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,25,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_6},	
//		//揉捏到顶/217
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,WAIST_POSITION+80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3},
//		//变换幅度的轻敲/222
//		//轻敲到肩部
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4,SPEED_3},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,WAIST_POSITION+0,KNEAD_RUN_STOP_AT_MED,1,KNOCK_RUN_STOP,1,4,SPEED_4},	
//		{BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_TOP,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_RUN_STOP,1,4,SPEED_3}	,*/
	
};



