////轻松按摩(有肩部位置检测),力度较弱//307
////stronger
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction2[] = 
{	
   //揉捏在最低点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
//揉捏在最高点电机正转，速度改变
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //20
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  //30
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
   {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //40
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
   //揉捏在随机位置电机正转，速度1-2-3改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
 //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
 
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  //60
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //70
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,25,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  //80
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //90
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},



{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
   //100
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
   //110
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
//揉捏在最高点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //120
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //130
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
   {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  //140
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //160
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},

 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
//    //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP          ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
//
// //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  //以下为正常动作	
//  //揉捶同步到底部（低速）
//  //{BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
// //上提   揉捏宽度：窄
// // {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
//  
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0}, 
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,20},
//  
// //
// //{BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0}, 
// //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
//
//  // 第一节  颈部来回敲打
// // {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
// //// {BACK_SUB_MODE_KNOCK,WALK_LOCATE_SHOULDER,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},	
// // {BACK_SUB_MODE_KNOCK,WALK_LOCATE_NeckMed,0,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  //第 2 节  FULL RUBBING	
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T1,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_5,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_5,0},
//  //
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T2,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,10},
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T3,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2 ,_3D_SPEED_5,10},   
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T4,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},   
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T5,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3 ,_3D_SPEED_6,10},   
//   
//  //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T6,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,          0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},// 
//
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//  
//  
//  
//  //
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T6,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,POSITION_T5,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2 ,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,POSITION_T4,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,POSITION_T3,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1 ,_3D_SPEED_5,10},
//  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,POSITION_T2,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
// // {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck         ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  
//  // 第 3 节 MIN/////////////////////////////////////////////////////////
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  //{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  //{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST     ,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
////
//
//  ////第 10 节 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,80,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,2, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,2, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0}, 
//
//
//
//
//
//
//
//
//
////第  4 节 
//  //{BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_4,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0}, 
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},  
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
////
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//////////////////////////////////////////////////////////
//  
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PressNeck,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
///////添加茶油
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE ,40,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE ,40,KNEAD_STOP       ,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE  ,0,KNEAD_STOP       ,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE  ,0,KNEAD_STOP       ,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},//
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE ,40,KNEAD_STOP       ,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNOCK  ,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
////2////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//   {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,40,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},/////////
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},/////////
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,40,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  
//  
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10}, 
//
//
////3
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},///////
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,40,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MAX,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//////4//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_9_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},////////////
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_WAIST,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MED,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN,0,0,SPEED_4,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_5,10}, 
//
//
///////茶油  结束
/////press/////第 7 节 //////////////////////////////////////////////////////////////////////////////
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,10,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,10,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,10,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//
////
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
// // {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
// 
// 
//  //搓背  第 8 节 
//  //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,          0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T6,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T5,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3 ,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T4,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T3,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2 ,_3D_SPEED_5,10},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,POSITION_T2,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,10},
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  
//  
//  //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//
//  //在腰部来回揉捏  第 9 节 
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST       ,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_4_10,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_2_10,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_WAIST       ,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_9_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_8_10,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_7_10,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_5_10,80,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_4_10,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,30,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  ////第 10 节 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4, SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,2, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,40,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,80,KNEAD_STOP,0,KNOCK_RUN_STOP,1,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,2, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,2, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,3, SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_ABSULATE,0,KNEAD_STOP,0,KNOCK_RUN_STOP,6,4, SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_5,0},
//  
//  
//  
//  
//  
//  
//  
//  
//  
//  //屁股 第 11 节 
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP          ,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP          ,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP           ,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,5,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,30,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,35,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK,40,KNEAD_STOP,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_5,0},
//  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,50,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_5,0},
//  
//  //搓背  第 12 节 
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_5,0},
//  
//  //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,          0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4,/_3D_SPEED_3,0},
// // {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T6,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_3,10},
//  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T5,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_4 ,_3D_SPEED_3,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T4,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_3,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T3,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3 ,_3D_SPEED_3,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_ABSULATE,POSITION_T2,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_3,10},
//  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PressNeck,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_3,0},
//  
//  
// // {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_3,_3D_SPEED_3,0},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_3,0},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_3,0},
//  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_3,0},

};