
//舒展按摩（宽幅度按摩）中等力度
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction1[] = 
{	
  //揉捏在最低点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
//揉捏在最高点电机正转，速度改变
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //20
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //10
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //20
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,2,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,2,SPEED_1},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //20
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  //30
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //40
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
   //揉捏在随机位置电机正转，速度1-2-3改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
 //50
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
 
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  //60
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //70
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
 
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,25,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  //80
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //90
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},



{BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
   //100
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  
 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
   //110
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
 
//揉捏在最高点电机正转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_RUN,2,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,4,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_RUN,2,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  //120
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  
  
  //揉捏在最高点电机反转，速度改变
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_3},
  //130
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_1},
  
   //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,20,KNEAD_UNRUN,4,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_UNRUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
   {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,4,SPEED_3},
  //140
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_UNRUN,3,SPEED_2},
  //160
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},

 //揉捏在随机位置电机正转，速度3-2-1改变
 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_3},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_3},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,20,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,15,KNEAD_RUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_1},
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_1},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_TOP,15,KNEAD_UNRUN,4,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN,0,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,3,SPEED_2},
} ;

